rootProject.name = "YouTubeRatingApp"

includeBuild("build-logic")

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
        // Kotlin Gradle plugin / compiler builds (used when a fix isn't on the plugin portal yet).
        maven("https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev")
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven("https://jitpack.io")
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    }
}

include(":shared")
include(":core:core-domain")
include(":core:core-data")
include(":core:core-presentation")
include(":core:core-design-system")
include(":composeApp")
include(":androidApp")
include(":desktopApp")
include(":webApp")
if (providers.gradleProperty("enableIosBuild").map(String::toBoolean).getOrElse(false)) {
    include(":iosComposeApp")
}
include(":feature:habittracker-data")
include(":feature:habittracker-domain")
include(":feature:habittracker-presentation")
include(":feature:running-data")
include(":feature:running-domain")
include(":feature:running-presentation")
include(":feature:home-data")
include(":feature:home-domain")
include(":feature:home-presentation")
include(":feature:rating-data")
include(":feature:rating-domain")
include(":feature:rating-presentation")
include(":feature:favorites-data")
include(":feature:favorites-domain")
include(":feature:favorites-presentation")
include(":feature:watchhistory-data")
include(":feature:watchhistory-domain")
include(":feature:watchhistory-presentation")
include(":feature:offlinevideos-data")
include(":feature:offlinevideos-domain")
include(":feature:offlinevideos-presentation")
include(":feature:gallery-data")
include(":feature:gallery-domain")
include(":feature:gallery-presentation")
include(":feature:ratedvideos-data")
include(":feature:ratedvideos-domain")
include(":feature:ratedvideos-presentation")
include(":feature:bible-data")
include(":feature:bible-domain")
include(":feature:bible-presentation")
include(":feature:gospel-data")
include(":feature:gospel-domain")
include(":feature:gospel-presentation")
include(":feature:prayer-data")
include(":feature:prayer-domain")
include(":feature:prayer-presentation")
include(":feature:notes-data")
include(":feature:notes-domain")
include(":feature:notes-presentation")
include(":feature:calls-data")
include(":feature:calls-domain")
include(":feature:calls-presentation")
include(":feature:analytics-data")
include(":feature:analytics-domain")
include(":feature:analytics-presentation")
include(":feature:settings-data")
include(":feature:settings-domain")
include(":feature:settings-presentation")
include(":feature:kuiver-data")
include(":feature:kuiver-domain")
include(":feature:kuiver-presentation")
include(":feature:fasting-data")
include(":feature:fasting-domain")
include(":feature:fasting-presentation")
include(":feature:rosary-data")
include(":feature:rosary-domain")
include(":feature:rosary-presentation")
include(":feature:saints-data")
include(":feature:saints-domain")
include(":feature:saints-presentation")
include(":feature:spiritualtraining-data")
include(":feature:spiritualtraining-domain")
include(":feature:spiritualtraining-presentation")
// Most Android feature sources still compile from `:composeApp`; these modules are extraction targets for the migration.
