package com.youtube.rating.android.utils

/**
 * Types of changes that trigger auto-backup.
 */
enum class ChangeType {
    NOTE_ADDED,
    NOTE_UPDATED,
    NOTE_DELETED,
    FAVORITE_ADDED,
    FAVORITE_REMOVED,
    FAVORITE_UPDATED,
    FAVORITE_CLEARED,
    OFFLINE_VIDEO_ADDED,
    OFFLINE_VIDEO_REMOVED,
    OFFLINE_VIDEO_UPDATED,
    OFFLINE_VIDEO_CLEARED,
    ROSARY_SESSION_UPDATED,
    ROSARY_SETTINGS_UPDATED,
    TASK_UPDATED,
    FASTING_UPDATED,
    BIBLE_PLANNER_UPDATED,
    BIBLE_HIGHLIGHT_UPDATED,
    BIBLE_PROGRESS_UPDATED,
    THEME_CHANGED,
    CUSTOM_NOVENA_UPDATED,
    SAVED_PSALM_UPDATED,
    GALLERY_UPDATED,
    TRAINING_UPDATED,
    SETTINGS_UPDATED
}
