# YouTube Ratings iOS - CocoaPods Configuration
# This Podfile manages native iOS dependencies while KMP modules are provided as XCFrameworks

platform :ios, '15.0'

target 'iosApp' do
  # Network & HTTP
  pod 'Alamofire', '~> 5.8'
  
  # Reactive Programming
  pod 'RxSwift', '~> 6.5'
  pod 'RxCocoa', '~> 6.5'
  
  # Async/Await Utilities
  pod 'AsyncHTTPClient', '~> 1.19'
  
  # Video Playback
  pod 'GoogleAds-IMA-iOS-SDK', '~> 3.18'
  
  # LiveKit Integration
  pod 'LiveKit', :git => 'https://github.com/livekit/client-sdk-swift.git', :branch => 'main'
  
  # Analytics
  pod 'Mixpanel', '~> 4.1'
  
  # Crash Reporting
  pod 'Sentry', '~> 8.1'
  
  # Local Storage
  pod 'SQLCipher', '~> 4.5'
  
  # UI Components
  pod 'SnapKit', '~> 5.6'
  pod 'Kingfisher', '~> 7.8'
  
  # Utilities
  pod 'SwiftyJSON', '~> 5.0'
  pod 'KeychainAccess', '~> 4.2'
  
  # Development Pods
  target 'iosAppTests' do
    inherit! :search_paths
    pod 'Quick', '~> 7.5'
    pod 'Nimble', '~> 12.1'
    pod 'RxTest', '~> 6.5'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'COCOAPODS=1',
      ]
      
      # Swift optimization settings
      if config.name == 'Release'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Osize'
        config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
      else
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      end
      
      # Suppress warnings from pods
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
    end
  end
end
